"use client"

import { useState } from "react"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Textarea } from "@/components/ui/textarea"
import { Label } from "@/components/ui/label"
import { Badge } from "@/components/ui/badge"
import { Progress } from "@/components/ui/progress"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import {
  ArrowLeft,
  Zap,
  FileText,
  Shield,
  AlertTriangle,
  CheckCircle,
  Brain,
  Target,
  TrendingUp,
  Eye,
} from "lucide-react"
import Link from "next/link"

interface AIInsight {
  type: "strength" | "gap" | "risk" | "recommendation"
  priority: "high" | "medium" | "low"
  title: string
  description: string
  action?: string
}

interface CaseAnalysis {
  completenessScore: number
  riskLevel: "low" | "medium" | "high" | "critical"
  evidenceStrength: number
  legalViability: number
  insights: AIInsight[]
}

export default function AIAssistant() {
  const [rawNarrative, setRawNarrative] = useState("")
  const [generatedReport, setGeneratedReport] = useState("")
  const [isGenerating, setIsGenerating] = useState(false)
  const [caseAnalysis, setCaseAnalysis] = useState<CaseAnalysis>({
    completenessScore: 75,
    riskLevel: "medium",
    evidenceStrength: 80,
    legalViability: 85,
    insights: [
      {
        type: "strength",
        priority: "high",
        title: "Strong Timeline Documentation",
        description: "Your incident timeline shows clear chronological progression with specific dates and times.",
        action: "Continue documenting any new incidents with similar detail",
      },
      {
        type: "gap",
        priority: "medium",
        title: "Missing Witness Information",
        description: "Consider adding contact details for witnesses mentioned in your account.",
        action: "Reach out to potential witnesses for statements",
      },
      {
        type: "risk",
        priority: "high",
        title: "Potential Retaliation Risk",
        description: "Based on the power dynamics described, there may be risk of workplace retaliation.",
        action: "Document any changes in work assignments or treatment",
      },
      {
        type: "recommendation",
        priority: "medium",
        title: "Legal Consultation Recommended",
        description: "Your case shows strong legal merit. Consider consulting with a PoSH specialist lawyer.",
        action: "Schedule consultation within 2 weeks",
      },
    ],
  })

  const generateReport = async () => {
    if (!rawNarrative.trim()) return

    setIsGenerating(true)

    // Simulate AI processing
    setTimeout(() => {
      const report = `COMPREHENSIVE INCIDENT REPORT
Generated by AI Assistant - ${new Date().toLocaleDateString()}

EXECUTIVE SUMMARY:
This report documents incidents of workplace harassment as described by the complainant. The AI analysis indicates strong documentation with clear patterns of inappropriate behavior that constitute violations under the Prevention of Sexual Harassment (PoSH) Act, 2013.

INCIDENT ANALYSIS:
${rawNarrative
  .replace(/I felt/g, "The complainant experienced")
  .replace(/he/g, "the respondent")
  .replace(/she/g, "the respondent")
  .replace(/really uncomfortable/g, "significant distress")
  .replace(/weird/g, "inappropriate and unprofessional")
  .replace(/creepy/g, "predatory behavior")}

LEGAL FRAMEWORK:
This incident falls under Section 2(n) of the PoSH Act, 2013, which defines sexual harassment as unwelcome acts or behavior including:
- Physical contact and advances
- Demand or request for sexual favors  
- Making sexually colored remarks
- Showing pornography
- Any other unwelcome physical, verbal or non-verbal conduct of sexual nature

RISK ASSESSMENT:
- Workplace Safety Risk: MEDIUM
- Retaliation Risk: HIGH
- Legal Viability: STRONG
- Evidence Strength: GOOD

RECOMMENDED ACTIONS:
1. File formal complaint with Internal Complaints Committee (ICC)
2. Request interim relief measures for safety
3. Document any subsequent incidents or retaliation
4. Seek legal consultation for case strategy
5. Consider counseling support for emotional well-being

AI CONFIDENCE LEVEL: 92%
This analysis is based on established legal precedents and PoSH Act guidelines.`

      setGeneratedReport(report)
      setIsGenerating(false)
    }, 3000)
  }

  const getInsightIcon = (type: string) => {
    switch (type) {
      case "strength":
        return <CheckCircle className="h-4 w-4 text-green-600" />
      case "gap":
        return <AlertTriangle className="h-4 w-4 text-orange-600" />
      case "risk":
        return <AlertTriangle className="h-4 w-4 text-red-600" />
      case "recommendation":
        return <Target className="h-4 w-4 text-blue-600" />
      default:
        return <Brain className="h-4 w-4 text-gray-600" />
    }
  }

  const getPriorityColor = (priority: string) => {
    switch (priority) {
      case "high":
        return "bg-red-100 text-red-800 border-red-200"
      case "medium":
        return "bg-yellow-100 text-yellow-800 border-yellow-200"
      case "low":
        return "bg-green-100 text-green-800 border-green-200"
      default:
        return "bg-gray-100 text-gray-800 border-gray-200"
    }
  }

  const getRiskColor = (risk: string) => {
    switch (risk) {
      case "critical":
        return "text-red-800"
      case "high":
        return "text-red-600"
      case "medium":
        return "text-orange-600"
      case "low":
        return "text-green-600"
      default:
        return "text-gray-600"
    }
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-green-50 to-blue-50">
      <div className="container mx-auto px-4 py-8">
        {/* Header */}
        <div className="flex items-center mb-8">
          <Link href="/">
            <Button variant="ghost" size="sm" className="mr-4">
              <ArrowLeft className="h-4 w-4 mr-2" />
              Back
            </Button>
          </Link>
          <div>
            <h1 className="text-3xl font-bold text-gray-900">AI Assistant</h1>
            <p className="text-gray-600">Intelligent support for documentation and case analysis</p>
          </div>
        </div>

        <Tabs defaultValue="narrative" className="w-full">
          <TabsList className="grid w-full grid-cols-4">
            <TabsTrigger value="narrative">Narrative Assistant</TabsTrigger>
            <TabsTrigger value="analysis">Case Analysis</TabsTrigger>
            <TabsTrigger value="evidence">Evidence Manager</TabsTrigger>
            <TabsTrigger value="escalation">Auto-Escalation</TabsTrigger>
          </TabsList>

          {/* Narrative Assistant */}
          <TabsContent value="narrative" className="space-y-6">
            <div className="grid lg:grid-cols-2 gap-8">
              <Card>
                <CardHeader>
                  <CardTitle className="flex items-center">
                    <FileText className="h-5 w-5 text-green-600 mr-2" />
                    Your Story
                  </CardTitle>
                  <CardDescription>
                    Share your experience in your own words. AI will help create a formal report.
                  </CardDescription>
                </CardHeader>
                <CardContent>
                  <Textarea
                    placeholder="Describe what happened in detail. Include when, where, who was involved, what was said or done, and how it affected you. The AI will help transform this into a professional legal document."
                    value={rawNarrative}
                    onChange={(e) => setRawNarrative(e.target.value)}
                    className="min-h-[300px]"
                  />
                  <Button
                    onClick={generateReport}
                    disabled={!rawNarrative.trim() || isGenerating}
                    className="w-full mt-4 bg-green-600 hover:bg-green-700"
                  >
                    {isGenerating ? (
                      <>
                        <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white mr-2"></div>
                        AI is analyzing and generating report...
                      </>
                    ) : (
                      <>
                        <Zap className="h-4 w-4 mr-2" />
                        Generate Professional Report
                      </>
                    )}
                  </Button>
                </CardContent>
              </Card>

              <Card>
                <CardHeader>
                  <CardTitle className="flex items-center">
                    <Shield className="h-5 w-5 text-blue-600 mr-2" />
                    AI-Generated Report
                  </CardTitle>
                  <CardDescription>Professional, legally-sound documentation ready for submission</CardDescription>
                </CardHeader>
                <CardContent>
                  {generatedReport ? (
                    <div className="space-y-4">
                      <Textarea
                        value={generatedReport}
                        onChange={(e) => setGeneratedReport(e.target.value)}
                        className="min-h-[300px] font-mono text-sm"
                      />
                      <div className="flex gap-2">
                        <Button variant="outline" size="sm">
                          <FileText className="h-4 w-4 mr-2" />
                          Export PDF
                        </Button>
                        <Button variant="outline" size="sm">
                          <Eye className="h-4 w-4 mr-2" />
                          Preview
                        </Button>
                      </div>
                    </div>
                  ) : (
                    <div className="text-center py-16 text-gray-500">
                      <Brain className="h-16 w-16 mx-auto mb-4 opacity-30" />
                      <p>Your AI-generated report will appear here</p>
                      <p className="text-sm mt-2">Share your story to get started</p>
                    </div>
                  )}
                </CardContent>
              </Card>
            </div>
          </TabsContent>

          {/* Case Analysis */}
          <TabsContent value="analysis" className="space-y-6">
            <div className="grid lg:grid-cols-3 gap-8">
              <div className="lg:col-span-2 space-y-6">
                {/* Analysis Metrics */}
                <Card>
                  <CardHeader>
                    <CardTitle className="flex items-center">
                      <TrendingUp className="h-5 w-5 text-blue-600 mr-2" />
                      Case Strength Analysis
                    </CardTitle>
                  </CardHeader>
                  <CardContent>
                    <div className="grid grid-cols-2 gap-6">
                      <div>
                        <div className="flex items-center justify-between mb-2">
                          <Label>Case Completeness</Label>
                          <span className="text-2xl font-bold text-blue-600">{caseAnalysis.completenessScore}%</span>
                        </div>
                        <Progress value={caseAnalysis.completenessScore} className="h-2" />
                      </div>
                      <div>
                        <div className="flex items-center justify-between mb-2">
                          <Label>Evidence Strength</Label>
                          <span className="text-2xl font-bold text-green-600">{caseAnalysis.evidenceStrength}%</span>
                        </div>
                        <Progress value={caseAnalysis.evidenceStrength} className="h-2" />
                      </div>
                      <div>
                        <div className="flex items-center justify-between mb-2">
                          <Label>Legal Viability</Label>
                          <span className="text-2xl font-bold text-purple-600">{caseAnalysis.legalViability}%</span>
                        </div>
                        <Progress value={caseAnalysis.legalViability} className="h-2" />
                      </div>
                      <div>
                        <div className="flex items-center justify-between mb-2">
                          <Label>Risk Level</Label>
                          <span className={`text-2xl font-bold ${getRiskColor(caseAnalysis.riskLevel)}`}>
                            {caseAnalysis.riskLevel.toUpperCase()}
                          </span>
                        </div>
                        <div className="text-sm text-gray-600">Workplace safety assessment</div>
                      </div>
                    </div>
                  </CardContent>
                </Card>

                {/* AI Insights */}
                <Card>
                  <CardHeader>
                    <CardTitle className="flex items-center">
                      <Brain className="h-5 w-5 text-purple-600 mr-2" />
                      AI Insights & Recommendations
                    </CardTitle>
                  </CardHeader>
                  <CardContent>
                    <div className="space-y-4">
                      {caseAnalysis.insights.map((insight, index) => (
                        <div key={index} className="border rounded-lg p-4">
                          <div className="flex items-start justify-between mb-2">
                            <div className="flex items-center">
                              {getInsightIcon(insight.type)}
                              <h4 className="font-medium ml-2">{insight.title}</h4>
                            </div>
                            <Badge className={getPriorityColor(insight.priority)}>{insight.priority} priority</Badge>
                          </div>
                          <p className="text-sm text-gray-700 mb-2">{insight.description}</p>
                          {insight.action && (
                            <div className="bg-blue-50 p-3 rounded-lg">
                              <p className="text-sm font-medium text-blue-900">Recommended Action:</p>
                              <p className="text-sm text-blue-800">{insight.action}</p>
                            </div>
                          )}
                        </div>
                      ))}
                    </div>
                  </CardContent>
                </Card>
              </div>

              {/* Sidebar */}
              <div className="space-y-6">
                <Card>
                  <CardHeader>
                    <CardTitle className="text-lg">AI Analysis Summary</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <div className="space-y-3">
                      <div className="flex justify-between">
                        <span className="text-sm text-gray-600">Overall Score</span>
                        <span className="font-medium">Strong Case</span>
                      </div>
                      <div className="flex justify-between">
                        <span className="text-sm text-gray-600">Confidence Level</span>
                        <span className="font-medium">92%</span>
                      </div>
                      <div className="flex justify-between">
                        <span className="text-sm text-gray-600">Next Review</span>
                        <span className="font-medium">In 7 days</span>
                      </div>
                    </div>
                  </CardContent>
                </Card>

                <Card className="bg-yellow-50 border-yellow-200">
                  <CardHeader>
                    <CardTitle className="text-lg text-yellow-800">Action Required</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <div className="space-y-2 text-sm text-yellow-700">
                      <p>• Gather witness contact information</p>
                      <p>• Document any new incidents</p>
                      <p>• Schedule legal consultation</p>
                      <p>• Review safety measures</p>
                    </div>
                  </CardContent>
                </Card>

                <Card>
                  <CardHeader>
                    <CardTitle className="text-lg">AI Capabilities</CardTitle>
                  </CardHeader>
                  <CardContent className="text-sm text-gray-600">
                    <div className="space-y-2">
                      <div className="flex items-center">
                        <CheckCircle className="h-4 w-4 text-green-600 mr-2" />
                        <span>Legal precedent analysis</span>
                      </div>
                      <div className="flex items-center">
                        <CheckCircle className="h-4 w-4 text-green-600 mr-2" />
                        <span>Evidence gap identification</span>
                      </div>
                      <div className="flex items-center">
                        <CheckCircle className="h-4 w-4 text-green-600 mr-2" />
                        <span>Risk assessment</span>
                      </div>
                      <div className="flex items-center">
                        <CheckCircle className="h-4 w-4 text-green-600 mr-2" />
                        <span>Timeline analysis</span>
                      </div>
                    </div>
                  </CardContent>
                </Card>
              </div>
            </div>
          </TabsContent>

          {/* Evidence Manager */}
          <TabsContent value="evidence" className="space-y-6">
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center">
                  <Shield className="h-5 w-5 text-indigo-600 mr-2" />
                  Intelligent Evidence Management
                </CardTitle>
                <CardDescription>AI-powered evidence organization and analysis</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="text-center py-16 text-gray-500">
                  <Shield className="h-16 w-16 mx-auto mb-4 opacity-30" />
                  <p>Evidence management features coming soon</p>
                  <p className="text-sm mt-2">AI will help organize and analyze your evidence</p>
                </div>
              </CardContent>
            </Card>
          </TabsContent>

          {/* Auto-Escalation */}
          <TabsContent value="escalation" className="space-y-6">
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center">
                  <AlertTriangle className="h-5 w-5 text-red-600 mr-2" />
                  Intelligent Auto-Escalation
                </CardTitle>
                <CardDescription>AI monitors your case and automatically escalates when needed</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="text-center py-16 text-gray-500">
                  <AlertTriangle className="h-16 w-16 mx-auto mb-4 opacity-30" />
                  <p>Auto-escalation system coming soon</p>
                  <p className="text-sm mt-2">AI will monitor risk levels and escalate automatically</p>
                </div>
              </CardContent>
            </Card>
          </TabsContent>
        </Tabs>
      </div>
    </div>
  )
}
